---

- name: Add snapcraft repo
  zypper_repository:
    repo: 'https://download.opensuse.org/repositories/system:/snappy/openSUSE_Leap_15.0'
    name: snappy
    state: present
    runrefresh: yes
    auto_import_keys: yes
  become: yes

- name: Install snapcraft
  zypper: 
    name: snapd
    state: latest
  become: yes

- name: Enable snapd
  systemd:
    name: snapd
    enabled: yes
    state: started
  become: yes