- hosts: localhost
  connection: local
  vars:
    terraform_version: 1.1.0
    install_gui_apps: no
    install_powerline: true
  roles:
    - role: common
    - role: snapcraft
    - role: develop
    - role: terminal
      vars:
        install_powerline: install_powerline 
    - role: terraform
    - role: git
    - role: gui-apps
      when: install_gui_apps == "yes"
    - role: rustlang
