---
  - name: set rust user path
    set_fact:
      rust_user_path: "{{ home_dir }}/.cargo/bin:{{ home_dir }}/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  - name: check if rustup is installed
    stat:
      path: "{{ home_dir }}/.rustup"
    register: rustup_directory_check
    changed_when: false
    failed_when: false

  - name: set rustup status
    set_fact:
      rustup_is_installed: "{{ rustup_directory_check.stat.exists }}"

  - name: check if rls is installed
    stat:
      path: "{{ home_dir }}/.cargo/bin/rls"
    register: rls_binary_check
    changed_when: false
    failed_when: false

  - name: set rls status
    set_fact:
      rls_is_installed: "{{ rls_binary_check.stat.exists }}"