---
- name: Create profile.d directory
  file:
    path: /etc/profile.d/
    state: directory
    recurse: yes
  become: true

- name: add rust utils to path
  template:
    src: rust.sh.j2
    dest: /etc/profile.d/rust.sh
    mode: 0644
  become: true
