---

  - include_tasks: ubuntu.yml
    when: ansible_distribution == "Ubuntu"

  - include_tasks: opensuse.yml
    when: ansible_distribution == "openSUSE Leap"

  - include_tasks: snap_apps.yml
    when: ansible_os_family != "Darwin"