---
- name: Add apt keys new way.
  ansible.builtin.get_url:
    url: "{{ item.value.key_url }}"
    dest: "/etc/apt/trusted.gpg.d/{{ item.key }}-keyring.asc"
    mode: '0644'
    force: true
  with_dict: "{{ gpg_keys }}"
  become: yes

- name: Remove old MySQL Workbench apt repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: absent
  loop:
    - deb http://repo.mysql.com/apt/ubuntu/ focal mysql-tools
    - "deb http://repo.mysql.com/apt/ubuntu/ {{ ansible_distribution_release }} mysql-tools"
    - "deb [signed-by=/etc/apt/trusted.gpg.d/mysql-keyring.asc] https://repo.mysql.com/apt/ubuntu/ {{ ansible_distribution_release }} mysql-tools"

- name: Add apt repositories
  become: yes
  apt_repository: 
    repo: "{{ item.value }}"
  with_dict: "{{ repositories.ubuntu }}"

- name: Install common packages
  apt: 
    name: "{{ packages.common }}"
    state: latest
    update_cache: yes
  become: yes

- name: Install ubuntu specific packages
  apt: 
    name: "{{ packages.ubuntu }}"
    state: latest
    update_cache: yes
  become: yes
