---
- name: Add apt keys from keyservers
  become: yes
  apt_key: 
    keyserver: "{{ item.value.keyserver }}" 
    id: "{{ item.value.key }}"
    state: present
  with_dict: "{{ gpg_key_servers }}"

- name: Add apt repositories
  become: yes
  apt_repository: 
    repo: "{{ item.value }}"
  with_dict: "{{ repositories.ubuntu }}"

- name: Install common packages
  apt: 
    name: "{{ packages.common }}"
    state: latest
    update_cache: yes
  become: yes

- name: Install ubuntu specific packages
  apt: 
    name: "{{ packages.ubuntu }}"
    state: latest
    update_cache: yes
  become: yes

- name: mysql-workbench | Install MySql Workbench
  apt: 
    name: mysql-workbench-community 
    state: latest
  become: yes