repositories:
  ubuntu:
    docker: "deb [signed-by=/etc/apt/trusted.gpg.d/docker-keyring.asc arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    sbt: "deb [signed-by=/etc/apt/trusted.gpg.d/sbt-keyring.asc arch=amd64] https://repo.scala-sbt.org/scalasbt/debian all main"
    terraform: "deb [signed-by=/etc/apt/trusted.gpg.d/terraform-keyring.asc arch=amd64] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main"
    github_cli: "deb [signed-by=/etc/apt/trusted.gpg.d/github_cli-keyring.gpg arch=amd64] https://cli.github.com/packages stable main"
    corretto: "deb [signed-by=/etc/apt/trusted.gpg.d/corretto-keyring.asc] https://apt.corretto.aws stable main"
  opensuse:
    corretto: "https://yum.corretto.aws/corretto.repo"
    github_cli: "https://cli.github.com/packages/rpm/gh-cli.repo"
gpg_key_urls:
  docker: 
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  terraform:
    url: https://apt.releases.hashicorp.com/gpg
    id: null
  corretto:
    url: https://apt.corretto.aws/corretto.key
    id: null
  # github_cli:
  #   url: https://cli.github.com/packages/githubcli-archive-keyring.gpg # Key is in binary.
  #   id: null
  sbt:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823
    id: null
gpg_key_servers:
  sbt: 
    keyserver: hkps://keyserver.ubuntu.com:443
    key: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
packages:
  ubuntu:
    - openjdk-11-jdk
    - docker-ce
    - docker-ce-cli
    - sbt
    - httpie
    - pass
    - maven
    - terraform
    - mysql-client-core-8.0
    - docker-compose
    - gh
    - java-17-amazon-corretto-jdk
    - scdaemon
    - gnupg2
    - gnupg-agent
    - pcscd
    - hopenpgp-tools 
    - yubikey-personalization
  pip:
    - semver
    - awscli
  opensuse:
    - git
    - docker
    - httpie
    - password-store
    - maven
    - python3-docker-compose
    - java-17-amazon-corretto-jdk
    - gh
  macos:
    - oracle-jdk
    - httpie
    - maven
    - docker
    - docker-compose
    - git
    - docker-credential-helper
    - 1password
    - sbt
    - gnu-tar
    - pinentry-mac

versions:
  maven: '3.8.6'