repositories:
  ubuntu:
    docker: "deb [signed-by=/etc/apt/trusted.gpg.d/docker-keyring.asc arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    sbt: "deb [signed-by=/etc/apt/trusted.gpg.d/sbt-keyring.asc arch=amd64] https://repo.scala-sbt.org/scalasbt/debian all main"
    terraform: "deb [signed-by=/etc/apt/trusted.gpg.d/terraform-keyring.asc arch=amd64] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main"
    # github_cli: "deb [signed-by=/etc/apt/trusted.gpg.d/github_cli-keyring.asc arch=amd64] https://cli.github.com/packages stable main"
    corretto: "deb [signed-by=/etc/apt/trusted.gpg.d/corretto-keyring.asc] https://apt.corretto.aws stable main"
    httpie: "deb [signed-by=/etc/apt/trusted.gpg.d/httpie-keyring.asc] https://packages.httpie.io/deb ./"
    1password: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/1password-keyring.asc] https://downloads.1password.com/linux/debian/amd64 stable main"
  opensuse:
    corretto: "https://yum.corretto.aws/corretto.repo"
    # github_cli: "https://cli.github.com/packages/rpm/gh-cli.repo"
gpg_key_urls:
  docker: 
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  terraform:
    url: https://apt.releases.hashicorp.com/gpg
    id: null
  corretto:
    url: https://apt.corretto.aws/corretto.key
    id: null
  httpie:
    url: https://packages.httpie.io/deb/KEY.gpg
    id: null
  1password:
    url: https://downloads.1password.com/linux/keys/1password.asc
    id: null
  # github_cli:
  #   url: https://cli.github.com/packages/githubcli-archive-keyring.gpg # Key is in binary.
  #   id: null
  sbt:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823
    id: null
gpg_key_servers:
  sbt: 
    keyserver: hkps://keyserver.ubuntu.com:443
    key: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  github-cli:
    keyserver: hkps://keyserver.ubuntu.com:443
    key: 23F3D4EA75716059
packages:
  debs:
    scala_cli:
      url: https://github.com/Virtuslab/scala-cli/releases/latest/download/scala-cli-x86_64-pc-linux.deb
  ubuntu:
    - docker-ce
    - docker-ce-cli
    - sbt
    - httpie
    - pass
    - terraform
    - mysql-client-core-8.0
    - docker-compose
    - gh
    - java-11-amazon-corretto-jdk
    - java-21-amazon-corretto-jdk
    - scdaemon
    - gnupg2
    - gnupg-agent
    - pcscd
    - hopenpgp-tools 
    - yubikey-personalization
    - 1password-cli
  pip:
    - semver
    - awscli
  opensuse:
    - git
    - docker
    - httpie
    - password-store
    - maven
    - python3-docker-compose
    - java-11-amazon-corretto-jdk
    - java-21-amazon-corretto-jdk
    - gh
  macos:
    - httpie
    - docker
    - docker-compose
    - git
    - docker-credential-helper
    - sbt
    - gnu-tar
    - pinentry-mac
    - 1password
    - 1password-cli
    - Virtuslab/scala-cli/scala-cli
    - corretto
    - gh
  homebrew:    
    - mongosh
    - maven
    - golang
    - neovim
    - jenv
    - gh
    # - openjdk@11
    # - openjdk@21
