repositories:
  ubuntu:
    mysql_workbench: deb http://repo.mysql.com/apt/ubuntu/ focal mysql-tools
  opensuse:
    google_chrome: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    vscode: https://packages.microsoft.com/yumrepos/vscode
  key_urls:
    - https://dl.google.com/linux/linux_signing_key.pub
    - https://packages.microsoft.com/keys/microsoft.asc
    - https://downloads.1password.com/linux/keys/1password.asc
    - https://repo.mysql.com/RPM-GPG-KEY-mysql-2022

gpg_keys:
  one_password:
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
    key_url: https://downloads.1password.com/linux/keys/1password.asc
  mysql:
    id: 3a79bd29
    key_url: https://repo.mysql.com/RPM-GPG-KEY-mysql-2023
packages:
  common:
    - gnome-keyring
  opensuse:
    - mysql-workbench
  ubuntu:
    - mysql-workbench-community
  snap:
    regular:
      - mailspring
      - yubioath-desktop
    classic:
      - code
      - intellij-idea-community
  macos:
    - obsidian
