---

- name: Configure git default editor
  git_config:
    name: core.editor
    scope: global
    value: "{{ git.editor }}"

- name: Configure git user name
  git_config:
    name: user.name
    scope: global
    value: "{{ git.user.name }}"

- name: Configure git user email 
  git_config:
    name: user.email
    scope: global
    value: "{{ git.user.email }}"

- name: Configure git user signing key
  git_config:
    name: user.signingkey
    scope: global
    value: "{{ git.user.signing_key }}"

- name: Configure commit auto signing
  git_config:
    name: commit.gpgsign
    scope: global
    value: "true"
