---
  - name: Add user to docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    become: yes
  
  - name: Enable and start docker service
    service:
      name: docker
      state: started
      enabled: yes
    become: yes
    when: ('"microsoft" not in ansible_kernel')

  - name: Download docker-credential-pass
    unarchive:
      src: https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-pass-v0.6.4-amd64.tar.gz
      remote_src: yes
      dest: /usr/local/bin
    become: yes
