- name: Download latest maven
  get_url:
    url: "https://dlcdn.apache.org/maven/maven-3/{{ maven.version }}/binaries/apache-maven-{{ maven.version }}-bin.zip"
    dest: /tmp
    mode: '0644'
    checksum: "sha512:{{ maven.shasum }}"

- name: Unzip maven
  ansible.builtin.unarchive:
    src: /tmp/apache-maven-{{ maven.version }}-bin.zip
    dest: /opt
  become: yes

- name: Create a sym link to maven
  file:
    src: /opt/apache-maven-{{ maven.version }}
    state: link
    dest: /opt/maven
  become: yes