- name: Refresh apt signing keys
  ansible.builtin.import_tasks: apt-keys.yml

- name: Add apt repositories
  become: yes
  apt_repository: 
    repo: "{{ item.value }}"
  with_dict: "{{ repositories.ubuntu }}"

- name: Install development related packages
  apt: 
    name: "{{ packages.ubuntu }}"
    state: latest
    update_cache: yes
  become: yes

- name: Install packages from url
  apt: 
    deb: "{{ item.value.url }}"
  with_dict: "{{ packages.debs }}"
  become: yes
