- name: Add apt keys from keyservers
  become: yes
  apt_key: 
    keyserver: "{{ item.value.keyserver }}" 
    id: "{{ item.value.key }}"
    state: present
  with_dict: "{{ gpg_key_servers }}"

# - name: Add apt keys
#   become: yes
#   apt_key:
#     url: "{{ item.value.url }}"
#     id: "{{ item.value.id }}"
#     state: present
#   with_dict: "{{ gpg_key_urls }}"

- name: Add apt keys new way.
  ansible.builtin.get_url:
    url: "{{ item.value.url }}"
    dest: "/etc/apt/trusted.gpg.d/{{ item.key }}-keyring.asc"
    mode: '0644'
    force: true
  with_dict: "{{ gpg_key_urls }}"
  become: yes

- name: Add apt repositories
  become: yes
  apt_repository: 
    repo: "{{ item.value }}"
  with_dict: "{{ repositories.ubuntu }}"

- name: Install development related packages
  apt: 
    name: "{{ packages.ubuntu }}"
    state: latest
    update_cache: yes
  become: yes

- name: Install packages from url
  apt: 
    deb: "{{ item.value.url }}"
  with_dict: "{{ packages.debs }}"
  become: yes