---

- name: Load "{{ ansible_system }} OS family variables.
  include_vars: "{{ ansible_system }}.yml"

- name: Ensure required packages are available.
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ terraform_dep_packages }}"
  become: yes

- name: Ensure install directory is available.
  file:
    path: "{{ terraform_install_dir }}"
    mode: 0755
    state: directory
  become: yes

- name: "Download terraform {{ terraform_version }} binary."
  unarchive:
    copy: no
    src:  "{{ terraform_download_url }}"
    dest: "{{ terraform_install_dir }}"
    creates: "{{ terraform_install_dir }}/terraform"
    mode: 0755
  become: yes

- name: Set symlink to /usr/local/bin/terraform.
  file:
    state: link
    src: "/usr/local/share/terraform/{{ terraform_version }}/terraform"
    dest: "/usr/local/bin/terraform"
  become: yes