---  
  - name: Load ubuntu specific variables
    include_vars: ubuntu.yml
    when: ansible_distribution == "Ubuntu"
  
  - name: Load opensuse specific variables
    include_vars: opensuse.yml
    when: ansible_distribution == "openSUSE Leap"

  - include_tasks: ubuntu.yml
    when: ansible_distribution == "Ubuntu"
  
  - include_tasks: opensuse.yml
    when: ansible_distribution == "openSUSE Leap"
  
  - include_tasks: docker_bash_completion.yml
  
  - name: Install git-prompt.sh
    copy:
      src: .bash
      dest: "{{ home_dir }}/"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r

  - name: Copy shell related files to home directory
    copy:
      src: "{{ item }}"
      dest: "{{ home_dir }}/{{ item }}"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r
    with_items: "{{ files_to_copy }}"

  - name: Create bash settings
    template: 
      src: bashrc.j2
      dest: "{{ home_dir }}/.bashrc"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r

  - name: Create powerline config directory
    file:
      path: "{{ home_dir }}/{{ powerline.config.path | dirname }}"
      state: directory
      recurse: yes
  
  - name: Copy powerline config
    copy:
      src: powerline-config.json
      dest: "{{ home_dir }}/{{ powerline.config.path }}"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r

  - name: Copy powerline themes
    copy:
      src: themes
      dest: "{{ home_dir }}/{{ powerline.config.path | dirname }}"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r

  # - name: Install Starship.rs
  #   snap:
  #     name: "starship"
  #     state: present
  #   become: yes

  - name: Configure Starship.rs
    copy:
      src: "starship.toml"
      dest: "{{ home_dir }}/.config/starship.toml"
      owner: "{{ ansible_user_id }}"
      mode: u=rw,g=r,o=r